[tracing.console]
enabled = false

[tracing.stdout]
enabled = true
format = "full"
filters.default = "debug"
filters.hyper = "info"

[http]
# address = "0.0.0.0"
port = 8080

[http.admin.auth]
username = "username"
password = "password"

[http.api1.asset]
maxage = 604800 # 1 week

[http.api1.search]
limit.default = 100
limit.max = 500
limit.depth = 2
fields.exdschema = "Name,Singular,Icon"
transient.exdschema = ""

[http.api1.sheet]
limit.default = 100
limit.max = 500
limit.depth = 2
list.fields.exdschema = "Name,Singular,Icon"
list.transient.exdschema = ""
entry.fields.exdschema = "*"
entry.transient.exdschema = "*"

[read.language]
default = "tc"
# This configuration is set up for the TW / Traditional Chinese game client, which does not seem to ship data for any other language.
exclude = ["ja", "en", "de", "fr", "chs", "cht", "kr"]

[version]
interval = 3600 # 1 hour
directory = "versions"
repositories = [
  "0b90d03e", # ffxiv
  "be3c0f25", # ex1 (hw)
  "27355e9f", # ex2 (stb)
  "50326e09", # ex3 (shb)
  "ce56fbaa", # ex4 (ew)
  "b951cb3c", # ex5 (dt)
]

[version.thaliak]
endpoint = "https://thaliak.xiv.dev/graphql/2022-08-14"

# Thaliak bugged out and failed to link between the last delta patch, and the history patches, at 7.0.
# This is just a manual specification of those links to restore the patch chain.
[version.thaliak.overrides]
# Seemingly not needed for the TW version. There are no history patches for it.

[version.patch]
directory = "patches"
concurrency = 4
user_agent = "FFXIV PATCH CLIENT"

[schema]
default = "exdschema"
interval = 3600       # 1 hour

[schema.exdschema]
default = "2:ver:request"
remote = "https://github.com/xivdev/EXDSchema.git"
directory = "exdschema"

[search.sqlite]
directory = "search"

[search.sqlite.cursor]
ttl = 3600 # 1 hour
tti = 300  # 5 minutes
